
import React from 'react';
import { Chart as ChartJS, ArcElement, Tooltip, Legend } from 'chart.js';
import { Pie } from 'react-chartjs-2';

ChartJS.register(ArcElement, Tooltip, Legend);

interface BatchAnalyticsReportProps {
    batchName: string;
    createdAt: string;
    stats: {
        total: number;
        success: number;
        failed: number;
        pending: number;
    };
    failedEmails: {
        technical: any[];
        compliance: any[];
    };
}

export const BatchAnalyticsReport = ({ batchName, createdAt, stats, failedEmails }: BatchAnalyticsReportProps) => {
    const chartData = {
        labels: ['Success', 'Failed', 'Pending'],
        datasets: [
            {
                data: [stats.success, stats.failed, stats.pending],
                backgroundColor: [
                    '#22c55e', // green-500
                    '#ef4444', // red-500
                    '#eab308', // yellow-500
                ],
                borderWidth: 1,
            },
        ],
    };

    const hasFailures = failedEmails.technical.length > 0 || failedEmails.compliance.length > 0;

    return (
        <div
            id="batch-analytics-report"
            className="bg-white p-8 w-[210mm] min-h-[297mm] mx-auto" // A4 width
            style={{ position: 'absolute', top: '-10000px', left: '-10000px' }} // Hidden off-screen
        >
            {/* Header */}
            <div className="border-b pb-6 mb-8 flex justify-between items-center">
                <div>
                    <h1 className="text-3xl font-bold text-gray-900 mb-2">Batch Delivery Report</h1>
                    <p className="text-gray-500">Generated by SendCertificates</p>
                </div>
                <div className="text-right">
                    <p className="text-xl font-semibold text-gray-800">{batchName}</p>
                    <p className="text-gray-500">{new Date(createdAt).toLocaleDateString()}</p>
                </div>
            </div>

            {/* Summary Stats */}
            <div className="grid grid-cols-4 gap-4 mb-8">
                <div className="bg-gray-50 p-4 rounded-lg border text-center">
                    <p className="text-gray-500 text-sm uppercase tracking-wider">Total Recipients</p>
                    <p className="text-3xl font-bold text-gray-900">{stats.total}</p>
                </div>
                <div className="bg-green-50 p-4 rounded-lg border border-green-100 text-center">
                    <p className="text-green-600 text-sm uppercase tracking-wider">Delivered</p>
                    <p className="text-3xl font-bold text-green-700">{stats.success}</p>
                </div>
                <div className="bg-red-50 p-4 rounded-lg border border-red-100 text-center">
                    <p className="text-red-600 text-sm uppercase tracking-wider">Failed</p>
                    <p className="text-3xl font-bold text-red-700">{stats.failed}</p>
                </div>
                <div className="bg-yellow-50 p-4 rounded-lg border border-yellow-100 text-center">
                    <p className="text-yellow-600 text-sm uppercase tracking-wider">Pending</p>
                    <p className="text-3xl font-bold text-yellow-700">{stats.pending}</p>
                </div>
            </div>

            {/* Charts Section */}
            <div className="flex gap-8 mb-12">
                <div className="w-1/2">
                    <h3 className="text-lg font-semibold mb-4 border-b pb-2">Delivery Status</h3>
                    <div className="w-64 mx-auto">
                        <Pie data={chartData} />
                    </div>
                </div>
                <div className="w-1/2">
                    <h3 className="text-lg font-semibold mb-4 border-b pb-2">Performance Summary</h3>
                    <div className="space-y-4">
                        <div className="flex justify-between items-center bg-gray-50 p-3 rounded">
                            <span className="font-medium text-gray-700">Success Rate</span>
                            <span className="font-bold text-gray-900">
                                {stats.total > 0 ? ((stats.success / stats.total) * 100).toFixed(1) : 0}%
                            </span>
                        </div>
                        <div className="flex justify-between items-center bg-gray-50 p-3 rounded">
                            <span className="font-medium text-gray-700">Failure Rate</span>
                            <span className="font-bold text-gray-900">
                                {stats.total > 0 ? ((stats.failed / stats.total) * 100).toFixed(1) : 0}%
                            </span>
                        </div>
                    </div>
                </div>
            </div>

            {/* Failure Breakdown */}
            {hasFailures && (
                <div className="mb-8">
                    <h3 className="text-lg font-semibold mb-4 border-b pb-2 text-red-700">Failure Analysis</h3>

                    {failedEmails.technical.length > 0 && (
                        <div className="mb-6">
                            <h4 className="font-medium text-gray-800 mb-2">Technical Issues (Resendable)</h4>
                            <table className="w-full text-sm text-left border rounded overflow-hidden">
                                <thead className="bg-gray-100 uppercase text-gray-600 text-xs">
                                    <tr>
                                        <th className="px-4 py-2">Email</th>
                                        <th className="px-4 py-2">Reason</th>
                                        <th className="px-4 py-2">Retry Count</th>
                                    </tr>
                                </thead>
                                <tbody className="divide-y">
                                    {failedEmails.technical.slice(0, 10).map((fail, i) => (
                                        <tr key={i}>
                                            <td className="px-4 py-2">{fail.email}</td>
                                            <td className="px-4 py-2">{fail.reason}</td>
                                            <td className="px-4 py-2">{fail.retryCount}</td>
                                        </tr>
                                    ))}
                                </tbody>
                            </table>
                            {failedEmails.technical.length > 10 && (
                                <p className="text-gray-500 text-xs mt-1 italic">...and {failedEmails.technical.length - 10} more technical failures.</p>
                            )}
                        </div>
                    )}

                    {failedEmails.compliance.length > 0 && (
                        <div>
                            <h4 className="font-medium text-gray-800 mb-2">Compliance Issues (Permanent)</h4>
                            <table className="w-full text-sm text-left border rounded overflow-hidden">
                                <thead className="bg-gray-100 uppercase text-gray-600 text-xs">
                                    <tr>
                                        <th className="px-4 py-2">Email</th>
                                        <th className="px-4 py-2">Reason</th>
                                    </tr>
                                </thead>
                                <tbody className="divide-y">
                                    {failedEmails.compliance.slice(0, 10).map((fail, i) => (
                                        <tr key={i}>
                                            <td className="px-4 py-2">{fail.email}</td>
                                            <td className="px-4 py-2">{fail.reason}</td>
                                        </tr>
                                    ))}
                                </tbody>
                            </table>
                        </div>
                    )}
                </div>
            )}

            {/* Footer */}
            <div className="mt-12 pt-6 border-t text-center text-gray-400 text-sm">
                <p>Report generated on {new Date().toLocaleString()}</p>
                <p>www.sendcertificates.com</p>
            </div>
        </div>
    );
};
